name: Deploy Svelte to S3

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Set Environment Variables
        run: |
          if [ "${GITHUB_REF_NAME}" = "develop" ]; then
            echo "PUBLIC_API_BACKEND_URL=${{ secrets.PUBLIC_API_BACKEND_URL_DEV }}" >> $GITHUB_ENV
          elif [ "${GITHUB_REF_NAME}" = "main" ]; then
            echo "PUBLIC_API_BACKEND_URL=${{ secrets.PUBLIC_API_BACKEND_URL_PROD }}" >> $GITHUB_ENV
          else
            echo "PUBLIC_API_BACKEND_URL=http://localhost:8080" >> $GITHUB_ENV
          fi
        
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          
      # 1️⃣ Clonar el repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Configurar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # 3️⃣ Instalar dependencias
      - name: Install dependencies
        run: npm install

      # 4️⃣ Construir Svelte
      - name: Build Svelte app
        run: npm run build



      # 6️⃣ Definir bucket según la rama
      - name: Set S3 bucket
        id: bucket
        run: |
          if [ "${GITHUB_REF##*/}" == "main" ]; then
            echo "BUCKET_NAME=${{ secrets.S3_BUCKET_PROD }}" >> $GITHUB_ENV
          else
            echo "BUCKET_NAME=${{ secrets.S3_BUCKET_DEV }}" >> $GITHUB_ENV
          fi
          echo "Deploying branch ${GITHUB_REF##*/} to bucket $BUCKET_NAME"

      # 7️⃣ Subir a S3
      - name: Deploy to S3
        run: |
          aws s3 sync ./build s3://$BUCKET_NAME \
            --delete 
